file_by_col = {
    '': 'grey.jpeg',
    '🔴': 'red.jpeg',
    '🟡': 'yellow.jpeg',
    '🟢': 'green.jpeg',
    '🔵': 'blue.jpeg',
    '⚫️': 'black.jpeg',
    '🔴🟡': 'orange.jpeg',
    '🟡🔴': 'orange.jpeg',
    '🔴🟢': 'blue.jpeg',
    '🟢🔴': 'blue.jpeg',
    '🔴🔵': 'purple.jpeg',
    '🔵🔴': 'purple.jpeg',
    '🔴⚫️': 'red-black.jpeg',
    '⚫️🔴': 'red-black.jpeg',
    '🟡🟢': 'yellow-green.jpeg',
    '🟢🟡': 'yellow-green.jpeg',
    '🟡🔵': 'green.jpeg',
    '🔵🟡': 'green.jpeg',
    '🟡⚫️': 'yellow-black.jpeg',
    '⚫️🟡': 'yellow-black.jpeg',
    '🟢🔵': 'blue-green.jpeg',
    '🔵🟢': 'blue-green.jpeg',
    '🟢⚫️': 'green-black.jpeg',
    '⚫️🟢': 'green-black.jpeg',
    '🔵⚫️': 'blue-black.jpeg',
    '⚫️🔵': 'blue-black.jpeg',
}